name: Deploy to Vercel

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  VERCEL_PROJECT_NAME: nait-website

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Deploy to Vercel (Production)
        run: vercel deploy --prod --yes --name "$VERCEL_PROJECT_NAME" --token=${{ secrets.VERCELACTIONSECRET }}
